repos:
  - repo: local
    hooks:

      - id: black
        name: black
        language: system
        entry: poetry run black -l 79
        types: [python]
        stages: [commit]

      - id: flake8
        name: flake8
        language: system
        entry: >
               poetry run flake8
               --per-file-ignores '*/__init__.py: F401'
               --max-adjustable-complexity 8
        types: [python]
        stages: [commit]

      - id: isort
        name: isort
        language: system
        entry: >
               poetry run isort
               --multi-line 3
               --trailing-comma
               --use-parentheses
        types: [python]
        stages: [commit]
